### PR TITLE
Add API to display list of movies

### PR DESCRIPTION
**Pull request by Kamba56**
Added a section for the list to be displayed
Added an API and queried the API
Created a module to display list of movies on the homepage

### CODE REVIEW

**Comment by Sahar-SE** [comment]
Hey Musa, I have checked the codes it was according to the requirements in project and has the API connection and also the list of movies thanks😀

**Review by Sahar-SE — COMMENTED** [review]
## **STATUS: Required Changes 📢 ** 
------
### Hi @Kamba56 , 

image


- [ ] ** I have considered your PR it was according to requirements the only thing that you can do is to add a .gitignore file to avoid committing unnecessary files and use JavaScript best practices then you can merge it.😉** 


### Highlights:
 ✔️ Project is setup correctly
 ✔️ All linters are passing
✔️ Correct gitflow
✔️ Professional documentation

**Cheers and Happy coding! :clap: :clap: :clap:**

**Comment by Kamba56** [comment]
@Sahar-SE thank you for your review

**Review by Sahar-SE — COMMENTED** [review]
## **STATUS: APPROVED  🟢 ** 
------
### Hi @Kamba56 , 

**Great work on making a descriptive  PR title and a short summary describing introduced changes in more detail👏🏻** 

### Highlights:
 ✔️ Project is setup correctly
 ✔️ All linters are passing
✔️ Correct gitflow
✔️ Professional documentation
✔️ .gitignore file is used to avoid committing unnecessary files.
✔️ Branch has the name of the feature.
✔️ And this is amazing that you care about [DRY, KISS, and YAGNI](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/clean-code/lesson_DRY_KISS_YAGNI.md) rules..

Your project is complete! . There is nothing else to say other than... it's time to merge it 🍾🚢 :shipit: . Congratulations!  🎉💯🌟 

image

**Cheers and Happy coding! :clap: :clap: :clap:**

**Pull request merged**
